### ISSUE TITLE
Problem with packaging

### ISSUE THREAD

**Issue by gsikorski** [ahmadnassri/har-validator#107]
I have a task that packages my `node_mouldes` folder into debian. Unfortunately, current version of `har-validator` (and `request`, which depends on it) cannot be packaged, because of https://github.com/epoberezkin/ajv/issues/526. Debian packaging, and probably hundreds of other tools, including make, Perl, Python, etc. have issues dealing with `$` in the filename and ways to escape varies in each of them. This issue is actually resolved in the `ajv@6.4.0`, so you should be able to get it. Could you upgrade `ajv` module in your `package.json` to fix this issue?

**Comment by linux-man** [comment]
Ajv version conflicts with electron-builder dependency. Please consider upgrade of ajv to 6.x version if possible.
