### ISSUE TITLE
Update is-my-json-valid (Regular Expression Denial of Service attack vulnerability)

### ISSUE THREAD

**Issue by pmelisko** [ahmadnassri/har-validator#21]
Hi you should update your dependancy is-my-json-valid to 2.12.4 at least in package.json. Older versions are vulnerable to Regular Expression Denial of Service attack.

Ref: https://nodesecurity.io/advisories/76

Pull request by sdepold: #19

**Comment by ahmadnassri** [comment]
thx, resolved in `v2.0.6`
