### ISSUE TITLE
Separate Repos for library and CLI

### ISSUE THREAD

**Issue by MarkHerhold** [ahmadnassri/har-validator#38]
Having this library do two jobs (a validation library and a CLI) adds a lot of dependencies that are useless when used as a library (chalk and commander). Ideally there would be a module for each.

**Comment by ahmadnassri** [comment]
I have been thinking about the same thing actually... agreed.

**Comment by ahmadnassri** [comment]
removed in [`v4.0.0`](https://github.com/ahmadnassri/har-validator/releases/tag/v4.0.0) and new package available: [`har-cli`](https://github.com/ahmadnassri/har-cli) which will include more CLI utilities soon as well!
