### ISSUE TITLE
Use Ajv validator?

### ISSUE THREAD

**Issue by epoberezkin** [ahmadnassri/har-validator#39]
https://github.com/epoberezkin/ajv
It is faster, better supports references, etc. (see benchmark: https://github.com/ebdrup/json-schema-benchmark)
Disclaimer: I created it

**Comment by ahmadnassri** [comment]
will certainly give it a try  thanks.

**Comment by epoberezkin** [comment]
Thank you. I can make a PR.

**Comment by ahmadnassri** [comment]
@epoberezkin that would be a great first step!

**Comment by ahmadnassri** [comment]
resolved with [`v3.3.0`](https://github.com/ahmadnassri/har-validator/releases/tag/v3.3.0)
