### ISSUE TITLE
Bluebird is little heavy for such a lightwight lib

### ISSUE THREAD

**Issue by abhijeetkpawar** [ahmadnassri/har-validator#8]
BlueBird is approx. 460KB of package when downloaded as node module. This seems to be little heavy considering its usage in har-validator

**Comment by ahmadnassri** [comment]
you're absolutely correct!

**Comment by ahmadnassri** [comment]
as of `v2.0.0` the entire module is now Promise based, uses native Promise, in Node.js `0.12.x` and up, and uses `pinkie-promise` for backward compatibility
