### ISSUE TITLE
bin directory is not present anymore

### ISSUE THREAD

**Issue by bilby91** [ahmadnassri/har-validator#92]
Hello,

I'm using react-native and during the build process of the android application it uses that har-validator bin. Today I had to delete my node_modules directory and install all dependencies again and this broke my android building because har-validator bin not present any longer. I don't know if I was using a really old version before but I started using a pretty new version of react-native so I'm kind of confused.

Any help is more than welcome!

Thanks

**Comment by ahmadnassri** [comment]
hey @bilby91 mind telling me what the app is? or at least the dependency tree that might have lead to this issue?

as of [`v4.0`](https://github.com/ahmadnassri/har-validator/releases/tag/v4.0.0) the CLI has been split up into a separate repo

**Comment by bilby91** [comment]
@ahmadnassri Thanks for the reply!

I have found the difference in the dependencies that generated the issue. `react-native` dependes on `request ^2.79.0`. request 2.80.0 updated har-validator to 4.2 a few month ago. My installation was before this bump so after deleting the node_modules folder it started installing the newer version. I will report this in `react-native`. 

Thanks!
